### ISSUE TITLE
CSS深入理解之border

### ISSUE THREAD

**Issue by jxZhangLi** [jxZhangLi/blog#1]
### border-width 不支持百分比
- 本身的语义和使用场景决定的，首先边框不会因为设备大就按比例变大的 ( 百分比单位就不和语义 ) 
- border-width支持关键字thin(1px)，medium(默认值3px)，thick(5px)

### border-style类型
none | 定义无边框。
-- | --
hidden | 与 "none" 相同。不过应用于表时除外，对于表，hidden 用于解决边框冲突。
dotted | 定义点状边框。在大多数浏览器中呈现为实线。(IE7/8圆角)
dashed | 定义虚线。在大多数浏览器中呈现为实线。
solid | 定义实线。
double | 定义双线。双线的宽度等于 border-width 的值。![image](https://user-images.githubusercontent.com/16809535/32162769-159fc616-bd95-11e7-8b2a-b89a9fdaaf00.png)
groove | 定义 3D 凹槽边框。其效果取决于 border-color 的值。
ridge | 定义 3D 垄状边框。其效果取决于 border-color 的值。
inset | 定义 3D inset 边框。其效果取决于 border-color 的值。
outset | 定义 3D outset 边框。其效果取决于 border-color 的值。
inherit | 规定应该从父元素继承边框样式。

### border与color
- 当 border-color 没有设置颜色的时候它的边框颜色默认color的颜色，color设置成什么颜色，边框就会变成什么样的颜色
![image](https://user-images.githubusercontent.com/16809535/32162992-beee0098-bd95-11e7-812b-e80268da35b1.png)

### border与三角等图形构建
- 画一个三角形
```css
.triangle {
    width: 0;
    height: 0;
    border: 100px solid;
    border-color: red black #FFEB3B #00BCD4;
}
```
效果:
![image](https://user-images.githubusercontent.com/16809535/32164719-4bc55408-bd9b-11e7-8c9c-dd71f2858036.png)

- 画一个梯形
```css
.triangle {
    width: 600px;
    border: 100px solid;
    border-color: transparent transparent #9e9e9e;
}
```
效果:
![image](https://user-images.githubusercontent.com/16809535/32165227-0748f3e6-bd9d-11e7-9229-3a9482d05cfc.png)

### border与透明边框
 - 使用border变透明来增加区域，边框则使用内阴影
```css
    .checkbox{
    width: 16px;
    height: 16px;
    border: 2px solid transparent;
    box-shadow: inset 0 1px, inset 1px 0, inset -1px 0, inset 0 -1px;
    background-color: #fff;
    background-clip: content-box;
    color: #ccc;
   }
```
- drop-shadow可以给png图标赋色
