### ISSUE TITLE
CSS深入理解之padding

### ISSUE THREAD

**Issue by jxZhangLi** [jxZhangLi/blog#2]
### padding与容器的尺寸
对于 Block 水平元素
- 只要设置了padding 值，一定会影响尺寸
- width 非 auto, padding 影响尺寸
- width 为 auto 或 box-sizing: border-box, 同时 padding 值设置很大时，不影响尺寸

对于 inline 水平元素
- 水平 padding 影响尺寸，垂直 padding 不影响尺寸，但会影响背景色（占据空间）

如何利用该特性：

使用 padding 来设置  |  的宽高

```html
<div class="text">
   登录<span></span>注册
</div>
```
```css
span {
   padding: 12px 6px 1px;
   margin-left: 10px;
   border-left: 2px solid;
   font-size: 0;
   color: #686363;
}
```
###  padding负值和百分比值

- padding 不支持任何形式的负值
- padding 的百分比值是相对于宽度计算的

如何利用该特性：可以使用 `padding: 50%` 来实现一个正方形

### inline 水平元素的 padding 百分比值

- 同样相对于宽度计算
- 默认的高度宽度细节有差异 ( 内联元素的垂直方向 padding 会出现空白节点，导致宽高不相等 )

![image](https://user-images.githubusercontent.com/16809535/32217644-a48bc496-be63-11e7-921e-29cb7ea2b9f0.png)

- padding 会断行 ( 标签里面写文字会断行 )

![image](https://user-images.githubusercontent.com/16809535/32217255-5f59b924-be62-11e7-8ba1-d95227118b6a.png)

### padding与图形绘制

- 三条干效果

```css
.line {
	width: 150px;
	height: 30px;
	border-top: 30px solid;
	border-bottom: 30px solid;
	padding: 15px 0;
	background: #000;
        // 重点 -  规定背景的绘制区域
	background-clip: content-box;		
}
```
